apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-order-api
  labels:
    app: order-api
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: order-api
    name: {{ .Release.Name }}-order-api


