apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-product-api
  labels:
    app: product-api
spec:
  type: ClusterIP
  ports:
    - port: 8081
  selector:
    app: product-api
    name: {{ .Release.Name }}-product-api