apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  labels:
    app: product-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      name: product-api
      labels:
        app: product-api
    spec:
      containers:
        - name: product-api
          image: local/product-api:bda6720
          imagePullPolicy: Never
      restartPolicy: Always
